### ISSUE TITLE
Minor text coloring issues

### ISSUE THREAD

**Issue by krazyito65** [LanikSJ/slack-dark-mode#125] opened 2019-08-06 14:41 UTC
**Describe the bug**
I found a couple areas where the black text is slightly hard to read due to black text on a dark background.

**To Reproduce**
At the top left, open the dropdown for your workspace profile

**Screenshots**
![image](https://user-images.githubusercontent.com/479738/62582122-edfadf00-b870-11e9-8acd-5ff21a2dae57.png)

**Desktop (please complete the following information):**

-   OS: Ubuntu 19.04
-   Slack Version: 4.0

**Comment by krazyito65** [comment] 2019-08-06 20:38
![image](https://user-images.githubusercontent.com/479738/62575394-3f4ea280-b860-11e9-8e83-f92872b35520.png)

Found this on thread replies as well.

**Comment by mikepenz** [comment] 2019-08-06 21:54
@krazyito65 I don't know where I could find this second text

**Comment by krazyito65** [comment] 2019-08-06 21:56
Sorry, just open threads view in the sidebar:
![image](https://user-images.githubusercontent.com/479738/62580108-15e74400-b86b-11e9-8997-916e12b4678e.png)

**Comment by mikepenz** [comment] 2019-08-06 22:25
@krazyito65 can you check if this is already solved via: https://github.com/LanikSJ/slack-dark-mode/issues/125 ?

**Comment by krazyito65** [comment] 2019-08-06 22:36
![image](https://user-images.githubusercontent.com/479738/62582037-a3796280-b870-11e9-9e40-9ddbcea1c00a.png)
Looks better, the free version messages are still black.

The thread replies text in the sidebar is still messed up as well.

**Comment by LanikSJ** [comment] 2019-08-08 01:00
I see it also the hover works however the non hover looks black.  I'm having a hard time nailing down the CSS element to solve this.

**Comment by LanikSJ** [comment] 2019-08-08 01:00
Oops damn close button so close to comment. 😛

**Comment by mikepenz** [comment] 2019-08-08 10:15
@LanikSJ I checked. the problem is that this chart is an SVG (including the text) And it seems they switch out the SVG on hover. so there is no actual css associated with it :/

**Comment by krazyito65** [comment] 2019-08-08 15:11
Looks good on my end.

I think the only thing i see thats left for this, is the 'replies' on the thread sidebar

![image](https://user-images.githubusercontent.com/479738/62580108-15e74400-b86b-11e9-8997-916e12b4678e.png)

**Comment by mikepenz** [comment] 2019-08-08 15:12
If I only were able to see this somewhere :D

**Comment by krazyito65** [comment] 2019-08-08 15:17
Hmm...  Its in the right sidebar of the threads view

![image](https://user-images.githubusercontent.com/479738/62715257-c23d3d80-b9c5-11e9-9473-b6508f5b2b30.png)

**Comment by mikepenz** [comment] 2019-08-08 15:32
@krazyito65 found it :D

**Comment by LanikSJ** [comment] 2019-08-08 22:06
Merged in #132

**Closed by LanikSJ** 2019-08-08 22:06 UTC
