### ISSUE TITLE
Add option to not change sidebar colors

### ISSUE THREAD

**Issue by phillipthelen** [LanikSJ/slack-dark-mode#113] opened 2019-07-31 08:21 UTC
**Is your feature request related to a problem? Please describe.**
I am a part of multiple workspaces (as I'm sure most slack users are) and like to use different sidebar color schemes, to easily distinguish them. The dark mode CSS overrides the sidebar colors, so that only the header part and the workspace switcher use the chosen colors. 

**Describe the solution you'd like**
Having a command line argument to choose if the sidebar colors should be overwritten or not would be great, to allow for more customization!

**Comment by LanikSJ** [comment] 2019-07-31 23:27
Slack has 2 sidebars actually one with all the different workspaces and another with channel lists.  Please let me know which one you're talking about.  

Workspaces sidebar colors are controlled from the app itself and is out of scope of this project currently.

**Comment by phillipthelen** [comment] 2019-08-01 07:51
I was referring to the channel lists. Right now the script always changes that from the chosen color scheme to a dark one.

**Comment by LanikSJ** [comment] 2019-08-02 04:26
That's the same as #103

**Closed by LanikSJ** 2019-08-02 04:26 UTC

**Comment by benfrew13** [comment] 2019-08-14 23:37
Hi, I'm not sure that this is really a duplicate of #103. User custom CSS is still applied globally. Likewise, after applying the dark theme, it's no longer possible to change the theme colors from within the app. Overriding the default theme colors for the sidebar isn't the same result as not modifying it at all, unless there's something I missed.

**Comment by netengdj** [comment] 2019-09-06 15:13
I agree with this.  The script overwrites the chosen sidebar theme.  Now i don't mind the color choices made in this script but I would rather use my own.  I unfortunately am not allowed to upload a screenshot.  This is definitely NOT a duplicate of #103.  I would think that if you find the user has changed their sidebar from the default scheme, that should be respected and left alone.

**Comment by LanikSJ** [comment] 2019-09-06 15:41
It may not be a dupe of #103 but it's not functionality I'm willing to build as everyone has their own preference.  You're free to modify the `dark-theme.css` as you see fit.   At the top of the file change the var for `sidebar-bg-color` save and restart / reload Slack.

**Comment by krazyito65** [comment] 2019-09-06 15:45
No I think you misunderstand @LanikSJ, they mean they want to use slacks default sidebar colors.  So in essence, they want to REMOVE `sidebar-bg-color` from being overwritten by the main css.  This will allow them to have their own sidebar colors, set by slack itself, for each workspace.

**Comment by krazyito65** [comment] 2019-09-06 15:50
Unless there's a way to have my custom CSS file 'undo' what the main css does?

**Comment by LanikSJ** [comment] 2019-09-06 15:54
Ah okay I see that's a little more complicated as you'd have to remove all the CSS elements that have `sidebar-bg-color`.  This would require maintaining several versions of CSS which will be an overhead I'm not willing to commit to.  I would be more inclined to do so if the were themes with distinct differences not just sidebar.

**Comment by krazyito65** [comment] 2019-09-06 15:54
I see. Yea then that's a bit more complicated.

**Comment by benfrew13** [comment] 2019-09-06 16:52
Does the current dark theme do anything to the sidebar that can't be accomplished via a standard theme set by slack? If so, would it make sense to just remove the sidebar modification from dark-theme.css and instruct users to copy/past the theme code into slack preferences? This would have to be done for each workspace, which would be annoying, but it's just a couple clicks, and would carry over to the users' mobile apps as well.

**Comment by LanikSJ** [comment] 2019-09-06 18:04
The workspaces sidebar is set by the app itself.  If you're talking about the Channel / DM sidebar that's set by the project.  If you wanted to set the Channel / DM sidebar to default colors you'd need to remove all the CSS elements that have `sidebar-bg-color` in them or at least remove the property if the element has more then one property.

**Comment by krazyito65** [comment] 2019-09-06 18:41
Alternatively move the sidebar css to the custom file and commit it to the repo so users can manually remove it at their leisure, but again, that would requires maintaining multiple CSS files

**Comment by benfrew13** [comment] 2019-09-06 18:49
What I think would work well for those of us asking for this is if all the sidebar CSS could be kept in one section of `dark-theme.css`. That way it's just one block to comment out or delete. I was able to achieve the desired results by commenting out anything with `sidebar` in it, which at the time was three different blocks in different places.

**Comment by krazyito65** [comment] 2019-09-06 18:54
We'd be happy to review a PR if you can make the appropriate changes.
